sudo: required
services:
  - docker
before_install:
  - docker build -t hariomsaini/docker-react -f dockerfile.dev .
script:
  - docker run  hariomsaini/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-821335748506" 
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"